version: "3"

services:
  db:
    image: mongo
    restart: always 
    ports:
      - 27017:27017
    environment:
       MONGODB_DATABASE: payever
  test-db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGODB_DATABASE: payever-test
      
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=d_user
      - RABBITMQ_DEFAULT_PASS=d_password